### ISSUE TITLE
Working Example?

### ISSUE THREAD

**Issue by jhartlep** [tystuyfzand/gotify-mqtt#5]
Hi,
I finally got the plugin installed into my docker installation of gotity.
I configured (MQTT-Server and credentials) for the plugin via REST-API and enabled the plugin.

```
[
	{
		"id": 1,
		"name": "MQTT",
		"token": "xxxxx",
		"modulePath": "github.com/tystuyfzand/gotify-mqtt",
		"author": "Tyler Stuyfzand",
		"website": "https://meow.tf",
		"enabled": true,
		"capabilities": [
			"configurer",
			"messenger"
		]
	}
]
```

```
servers:
- address: 192.168.9.2:1883
  username: "gotify"
  password: "xxxxx"
  subscribe:
  - 'gotify/mqtt'
```

Now I tried to publish something to the topic "gotify/mqtt". But how exactly looks the publish topic and the body like?
